# Test playbook
---

- hosts: all
  become: true
  vars:
    NS: TRAVIS
    openio_bootstrap: true
  roles:
    - role: users
    - role: repository
      openio_repository_mirror_host: mirror2.openio.io
      openio_repository_no_log: false
    - role: gridinit
      openio_gridinit_namespace: "{{ NS }}"
      #openio_gridinit_per_ns: true
    - role: memcached
      openio_memcached_namespace: "{{ NS }}"
    - role: role_under_test
      openio_oioswift_namespace: "{{ NS }}"
      openio_oioswift_bind_interface: "{{ ansible_default_ipv4.alias }}"
      openio_oioswift_sds_proxy_url: "http://172.17.0.2:6006"   # docker image
      openio_oioswift_workers: 1
      # The following namespace is not the above one "{{ NS }}", but the one from the docker image
      openio_oioswift_sds_proxy_namespace: OPENIO   # docker image
      openio_oioswift_pipeline: "{{ pipeline_tempauth_iam }}"
      openio_oioswift_iam_policy:
        'travis:ci':
          Statement:
            - Sid: FullAccess
              Action:
                - 's3:*'
              Effect: Allow
              Resource:
                - '*'
        'travis:user1':
          Statement:
            - Sid: User1BucketAllObjects
              Action:
                - 's3:ListBucket'
                #- 's3:GetObject'
                - 's3:PutObject'
                - 's3:DeleteObject'
              Effect: Allow
              Resource:
                - '*'

      openio_oioswift_filter_tempauth:
        use: "egg:swift#tempauth"
        user_travis_ci: "TRAVIS_PASS .admin"
        user_travis_user1: "USER1_PASS .admin"
      openio_oioswift_filter_cache:
        use: "egg:swift#memcache"
        memcache_servers: "{{ openio_oioswift_bind_address }}:6019"
        memcache_max_connections: 50

      openio_oioswift_filter_swift3:
        use: "egg:swift3#swift3"
        force_swift_request_proxy_log: true
        s3_acl: true

        # Allow reading of object between users
        s3_acl_openbar: true

        check_bucket_owner: true
        location: "{{ openio_s3_region | d('us-east-1') }}"
        max_bucket_listing: 1000
        max_multi_delete_objects: 1000
        max_upload_part_num: 10000
        log_s3api_command: false
...
