# Test playbook
---

- hosts: all
  become: true
  vars:
    NS: TRAVIS
    openio_bootstrap: true
  roles:
    - role: users
    - role: repository
      openio_repository_mirror_host: mirror2.openio.io
      openio_repository_no_log: false
    - role: gridinit
      openio_gridinit_namespace: "{{ NS }}"
      openio_gridinit_per_ns: true
    - role: memcached
      openio_memcached_namespace: "{{ NS }}"
    - role: role_under_test
      openio_oioswift_namespace: "{{ NS }}"
      openio_oioswift_bind_interface: "{{ ansible_default_ipv4.alias }}"
      openio_oioswift_sds_proxy_url: "http://{{ lookup('env','IPVAGRANT') }}:6006"
      openio_oioswift_workers: 1
      # The following namespace is not the above one "{{ NS }}", but the one from the docker image
      openio_oioswift_sds_proxy_namespace: OPENIO
      openio_oioswift_pipeline: "{{ pipeline_tempauth }}"
      openio_oioswift_filter_tempauth:
        use: "egg:swift#tempauth"
        user_travis_ci: "TRAVIS_PASS .admin"
      openio_oioswift_filter_cache:
        use: "egg:swift#memcache"
        memcache_servers: "{{ openio_oioswift_bind_address }}:6019"
        memcache_max_connections: 50
...
